### ISSUE TITLE
Make cloudformation-cli-python-lib easy to install

### ISSUE THREAD

**Issue by ikben** [aws-cloudformation/aws-cloudformation-rpdk-python-plugin#50]
If I open `handlers.py` in my IDE, it shows me errors because it can't import cloudformation_cli_python_lib.

Looking at the readme, I can fix this with the following command, but it would be nice if I could do a `pip install -r requirements.txt` and get cloudformation_cli_python_lib from pypi

```
pip install -e 'git+https://github.com/aws-cloudformation/aws-cloudformation-rpdk-python-plugin.git#egg=cloudformation_cli_python_lib&subdirectory=src'
```

**Comment by wulfmann** [comment]
@ikben I believe the team owns the `aws-cloudformation-rpdk-python-plugin` name and will be updating the deploy to go there in the future.

**Comment by ikben** [comment]
They also added `cloudformation-cli-python-lib` to pypi.

I think that making the lib available without publishing the plugin might be a good compromise to protect people from starting a python provider by accident, while keeping the experience smooth for anyone testing out the beta version

**Comment by tobywf** [comment]
this is partially why it's currently a developer preview. while we're iterating quickly and we know there are gaps in the support library, i'd prefer not to confuse people with outdated libraries on PyPI. and keeping the plugin and the library in sync is important. but you're right, this is tedious at the moment and will improve in future!

**Comment by ikben** [comment]
@tobywf would you accept a PR to update the requirements.txt to point to cloudformation-cli-python-lib on github?

**Comment by tobywf** [comment]
absolutely, PRs are always welcome! i do think focusing on getting the plugin ready for devs to use will ultimately do more people right than diverting attention away to e.g. maintaining PyPI uploads. but i've been wrong before :sweat_smile:

**Comment by ikben** [comment]
I think my pull request creates extra work one time, when the support lib goes GA, it has to be reverted back (but I also have a bit of experience with being wrong)
