### ISSUE TITLE
models.ResourceModel should be a child class of BaseResourceModel

### ISSUE THREAD

**Issue by ikben** [aws-cloudformation/aws-cloudformation-rpdk-python-plugin#55]
ProgressEvent defines the type of `resourceModels` as `Optional[List[BaseResourceModel]]` if `ResourceModel` is not a subclass of this the typing will not match

**Comment by tobywf** [comment]
i thought it was?

https://github.com/aws-cloudformation/aws-cloudformation-rpdk-python-plugin/blob/9eda207789e9d904a529dff802f5c73addacb2a7/python/rpdk/python/templates/models.py#L38

mypy seems happy with this, is there any indication it doesn't work? we did have stronger guarantees around types via generics, but some IDEs struggled to auto-complete that (see #44 )

**Comment by ikben** [comment]
This may have been a race condition. In the sense that I generated the code before the type hint refactor was merged (and I didn't update my plugin since).

I'll close this and reopen the issue if it doesn't work after I updated everything on my side
